apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-diagnosis-v2
  namespace: default
spec:
  subjects:
    - user: "cluster.local/ns/default/sa/diagnosis-v2"
  roleRef:
    kind: ServiceRole
    name: "diagnosis-v2"