apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: timeservice
    version: v1
  name: timeservice
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timeservice
      version: v1
  template:
    metadata:
      labels:
        app: timeservice
        version: v1
    spec:
      containers:
      - env:
        - name: DOTNET_ENVIRONMENT
          value: Production
        image: pitstop/timeservice:1.0
        imagePullPolicy: IfNotPresent
        name: timeservice
      restartPolicy: Always

---



apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: invoiceservice
    version: v1
  name: invoiceservice
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoiceservice
      version: v1
  template:
    metadata:
      labels:
        app: invoiceservice
        version: v1
    spec:
      containers:
      - env:
        - name: DOTNET_ENVIRONMENT
          value: Production
        image: pitstop/invoiceservice:1.0
        imagePullPolicy: IfNotPresent
        name: invoiceservice
      restartPolicy: Always
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notificationservice
    version: v1
  name: notificationservice
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notificationservice
      version: v1
  template:
    metadata:
      labels:
        app: notificationservice
        version: v1
    spec:
      containers:
      - env:
        - name: DOTNET_ENVIRONMENT
          value: Production
        image: pitstop/notificationservice:1.0
        imagePullPolicy: IfNotPresent
        name: notificationservice
      restartPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workshopmanagementeventhandler
    version: v1
  name: workshopmanagementeventhandler
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshopmanagementeventhandler
      version: v1
  template:
    metadata:
      labels:
        app: workshopmanagementeventhandler
        version: v1
    spec:
      containers:
      - env:
        - name: DOTNET_ENVIRONMENT
          value: Production
        image: pitstop/workshopmanagementeventhandler:1.0
        imagePullPolicy: IfNotPresent
        name: workshopmanagementeventhandler
      restartPolicy: Always
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workshopmanagementapi
    version: v1
  name: workshopmanagementapi
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshopmanagementapi
      version: v1
  template:
    metadata:
      labels:
        app: workshopmanagementapi
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        image: pitstop/workshopmanagementapi:1.0
        imagePullPolicy: IfNotPresent
        name: workshopmanagementapi
        ports:
        - containerPort: 5200
      restartPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vehiclemanagementapi
    version: v1
  name: vehiclemanagementapi
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vehiclemanagementapi
      version: v1
  template:
    metadata:
      labels:
        app: vehiclemanagementapi
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        image: pitstop/vehiclemanagementapi:1.0
        imagePullPolicy: IfNotPresent
        name: vehiclemanagementapi
        ports:
        - containerPort: 5000
      restartPolicy: Always

---


apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customermanagementapi
    version: v1
  name: customermanagementapi-v1
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customermanagementapi
      version: v1
  template:
    metadata:
      labels:
        app: customermanagementapi
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        image: pitstop/customermanagementapi:1.0
        imagePullPolicy: IfNotPresent
        name: customermanagementapi
        ports:
        - containerPort: 5100
      restartPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
    version: v1
  name: webapp
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      version: v1
  template:
    metadata:
      labels:
        app: webapp
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        image: pitstop/webapp:1.0
        imagePullPolicy: IfNotPresent
        name: webapp
        ports:
        - containerPort: 7000
      restartPolicy: Always


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auditlogservice
    version: v1
  name: auditlogservice
  namespace: pitstop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auditlogservice
      version: v1
  template:
    metadata:
      labels:
        app: auditlogservice
        version: v1
    spec:
      containers:
      - env:
        - name: DOTNET_ENVIRONMENT
          value: Production
        image: pitstop/auditlogservice:1.0
        imagePullPolicy: IfNotPresent
        name: auditlogservice
      restartPolicy: Always

